---
title: "lecture review"
author: "Courtney Chan"
date: "November 7, 2018"
output: github_document
---


library(tidyverse)
library(rvest)
library(readr)
library(rnoaa)


df = data_frame(
  a = rnorm(20, 3, 1),
  b = rnorm(20, 0, 5),
  c = rnorm(20, 10, .2),
  d = rnorm(20, -3, 1)
)

mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}


mean_and_sd(df$a)
mean_and_sd(df$b)
mean_and_sd(df$c)
mean_and_sd(df$d)

output = map(df, mean_and_sd)


weather = 
  meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2016-01-01",
                      date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

weather

weather_nest = 
  nest(weather, date:tmin)

weather_nest

weather_lm = function(df) {
  lm(tmax ~ tmin, data = df)
}

weather_lm(weather_nest$data[[1]])

map(weather_nest$data, weather_lm)


wait maybe nest the total and unsolved into a data column

then create a function that can be applied to that list data column



?lm()

?prop.test()
